-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "lastX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lastY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "lastZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
